// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWo2kxSs_wYxHyfTjYhIXAdfiYPHcyrhE',
    appId: '1:1065173702077:web:0130632e3e5a2b5e182ed4',
    messagingSenderId: '1065173702077',
    projectId: 'track-hub-97eb8',
    authDomain: 'track-hub-97eb8.firebaseapp.com',
    storageBucket: 'track-hub-97eb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiLrLbBqrkY8_dfdkAi1ymlAP2-54Z_40',
    appId: '1:1065173702077:android:7af38d85d9f5e9ac182ed4',
    messagingSenderId: '1065173702077',
    projectId: 'track-hub-97eb8',
    storageBucket: 'track-hub-97eb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDinDRB4iRhG-SdJq8SnETBdJxvYMsX3RU',
    appId: '1:1065173702077:ios:941fb9e63d3c37f2182ed4',
    messagingSenderId: '1065173702077',
    projectId: 'track-hub-97eb8',
    storageBucket: 'track-hub-97eb8.appspot.com',
    iosBundleId: 'com.example.mbapProjectPart2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDinDRB4iRhG-SdJq8SnETBdJxvYMsX3RU',
    appId: '1:1065173702077:ios:941fb9e63d3c37f2182ed4',
    messagingSenderId: '1065173702077',
    projectId: 'track-hub-97eb8',
    storageBucket: 'track-hub-97eb8.appspot.com',
    iosBundleId: 'com.example.mbapProjectPart2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWo2kxSs_wYxHyfTjYhIXAdfiYPHcyrhE',
    appId: '1:1065173702077:web:c3d6c8a7c4382fd0182ed4',
    messagingSenderId: '1065173702077',
    projectId: 'track-hub-97eb8',
    authDomain: 'track-hub-97eb8.firebaseapp.com',
    storageBucket: 'track-hub-97eb8.appspot.com',
  );
}
